### ISSUE TITLE
nuxt3.7 devProxy for websocket not available

### ISSUE THREAD

**Issue by jktantan** [nuxt/cli#107]
### Environment

Nuxt 3.7

### Reproduction

Nuxt 3.7

### Describe the bug

Config:

``` javascript
nitro:{
  devProxy: {
    '/proxy': {
      target: `http://localhost:8080`,
      changeOrigin: true,
      ws: true,
    },
}
```

In web:
![image](https://github.com/nuxt/nuxt/assets/6302650/f4f3197c-35cb-4e6b-baa8-dbdb3fd9aefc)

![image](https://github.com/nuxt/nuxt/assets/6302650/bf966232-39d4-48da-a9b0-771f043d884e)

![image](https://github.com/nuxt/nuxt/assets/6302650/5c9cf877-8a6c-4357-97e8-620bbc98a71e)

If direct connect to Websocket Server:
![image](https://github.com/nuxt/nuxt/assets/6302650/b5008c97-7fa9-4a29-a92c-a8515b735034)

**Comment by pi0** [comment]
Thanks for the issue. I will be working on a quick solution to make it working again on nuxi 3.7 👍🏼

**Comment by vanling** [comment]
I hope when this is fixed the following works again

```package.json
{
  "name": "domain.nl",
  "private": true,
  "scripts": {
     "dev": "nuxt dev --host local.domain.nl --https --ssl-cert local.domain.nl.pem --ssl-key local.domain.nl-key.pem"
   }
}
```
_package.json_

**Comment by pi0** [comment]
host issue is fixed already in latest 3.7.2 cli release. Can you please confirm that? 🙏

**Comment by vanling** [comment]
@pi0 Replacing `nuxt dev` with `npx nuxi dev` > Still getting the error 

```- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
```

**Comment by jktantan** [comment]
> host issue is fixed already in latest 3.7.2 cli release. Can you please confirm that? 🙏

Unfortunately, it still doesn't work.

**Comment by pi0** [comment]
@jktantan I meant the host. WebSocket issue is not resolved yet.

**Comment by pi0** [comment]
With #127 ([v3.7.3](https://github.com/nuxt/cli/releases/tag/v3.7.3)), you can hook into the `listen` event to register a custom ws handler. Check out [this example](https://github.com/nuxt/cli/blob/main/playground/modules/ws.ts) for usage. 

Will be working on some upstream (nitro) fixes to fully unblock `devProxy` support as well 👍🏼

**Comment by jenjen75** [comment]
> With #127 ([v3.7.3](https://github.com/nuxt/cli/releases/tag/v3.7.3)), you can hook into the `listen` event to register a custom ws handler. Check out [this example](https://github.com/nuxt/cli/blob/main/playground/modules/ws.ts) for usage.
> 
> Will be working on some upstream (nitro) fixes to fully unblock `devProxy` support as well 👍🏼

Thank you @pi0 for the information ! This help me find a workaround
I use multiple Nuxt projects in iframe, in this case HMR does not work at all.
@jktantan @ucw maybe can be useful for you and anyone in this case :

```ts
import { defineNuxtConfig } from "nuxt/config"
import { createProxyServer } from "httpxy"

export default defineNuxtConfig({
  nitro: {
    devProxy: {
      // Not working
      "/editor/assets/": {
        target: "ws://localhost:5003/editor/assets/",
        ws: true
      }
    }
  },
  hooks: {
    // Workaround
    listen(server) {
      const proxy = createProxyServer({ target: { host: "localhost", port: 5003 } })

      server.on("upgrade", (req, socket, head) => {
        if (req.url === "/editor/assets/") {
          proxy.ws(req, socket, head) // socket has type error by it works
        }
      })
    }
  }
})

````

**Comment by dantio** [comment]
@jenjen75 Solution worked for me. Also, this gist can be helpful: 
https://gist.github.com/ucw/67f7291c64777fb24341e8eae72bcd24

**Comment by emilecaron** [comment]
same thing here. workaround was fine before upgrading to 3.11

**Comment by danwritecode** [comment]
any update on this? this is holding up a production deployment

**Comment by yochze** [comment]
any update on this?

**Comment by zhaoyuqiqi** [comment]
any update on this?

**Comment by emilecaron** [comment]
We eventually switched over to SEE which are working fine. But it won't suit every use case

**Comment by danielroe** [comment]
~~would you mind opening an issue upstream in nitro?~~

tracked in https://github.com/nitrojs/nitro/issues/4269

as far as I can tell, a `nitro.devProxy` entry with `ws: true` never sees the upgrade: nitro's dev server registers `devProxy` routes only as HTTP handlers, while `NitroDevServer.handleUpgrade` forwards unconditionally to the dev worker, so nothing consults `ws`. HTTP requests to the same path proxy correctly.

testing, the `nuxt.server.upgrade` workaround from this thread does still work on latest, and the bug still reproduces on nitro v3 so it isn't yet solved

cc: @pi0
