### ISSUE TITLE
Stackblitz PNPM `nuxi module add <module>` fails silently

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/cli#747]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.15.4
- CLI Version:      3.21.1
- Nitro Version:    2.10.4
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-wkxwpure?file=package.json

### Describe the bug

Running `nuxi module add <module>` fails silently when using PNPM on Stackblitz.

```
ℹ Resolved @nuxtjs/i18n, adding module...  
ℹ Installing @nuxtjs/i18n@9.2.0 as a dependency   
<dead>
```

No entries to the package.json or nuxt.config.

### Additional context

Works fine with NPM

_No response_

### Logs

```shell-script

```

**Comment by harlan-zw** [comment]
Maybe fixed with https://github.com/nuxt/cli/pull/717?

**Comment by BobbieGoede** [comment]
I can still reproduce with the latest release (which includes #717) on Stackblitz, but it works fine locally 🤔 

While checking this out I found that `nuxt dev` is also broken with nuxi/cli `3.22.2`, while working fine with `3.22.0` and `3.22.1`. Also only on Stackblitz, not necessarily related to this issue but will confuse anyone attempting to debug this issue.

Not sure how to debug this further 🤷

**Comment by danielroe** [comment]
Looking at this, it seems to crash at this line of code in `nypm`:

```ts
const { exitCode } = await x("corepack", ["--version"])
```

It's a bug in stackblitz, I'm sure. But perhaps we could early return with `false` if stackblitz environment is detected? cc: @pi0

**Comment by pi0** [comment]
reported upstream to tinyexec (https://github.com/tinylibs/tinyexec/issues/46)
